version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_monomap
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: